logging:
  level:
    web: TRACE
    org.springframework.web: TRACE
spring:
  datasource:
    url: jdbc:h2:mem:wb2
    driver-class-name: org.h2.Driver
    username: wb2-project
    password: wb2-project
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: local
token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351